### ISSUE TITLE
Do a release to PyPI

### ISSUE THREAD

**Issue by rufuspollock** [datopian/giftless#173]
Split out of #126

```[tasklist]
### Tasks
- [x] Add @athornton as maintainer on pypi for giftless so he can push
- [x] Do a release to pypi which covers ...
- [ ] https://github.com/datopian/giftless/issues/102
- [ ] https://github.com/datopian/giftless/issues/119
- [ ] Automate releases from tags (?)
```

**Comment by athornton** [comment]
I'm happy to push a new release if I'm empowered to do so, although we should definitely merge up that new auth work @vit-zikmund was working on and probably revisit the s3 signed URL thing too.

**Comment by rufuspollock** [comment]
@demenech any news on being to add @athornton to pypi as a maintainer on giftless so he can push etc ...

**Comment by rufuspollock** [comment]
Ok realise 🤦‍♂️ this is really a duplicate of #119 

Let’s close
