### ISSUE TITLE
[epic] Giftless documentation v1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/giftless#69]
We want to create some great giftless documentation so that it is easy for others to use and contribute to.

We already have pretty good docs but we need more info on getting started as an integrator and extender.

## Job Stories

When configuring and deploying giftless as a developer I want good documentation how to do that so that i can get started quickly

When I have my cloud storage I want to be able to us that storage with giftless e.g. via adding a new storage backend so that i can store data in my cloud storage

When wanting to control access to storage that giftless is the gatekeeper for I want to add/customize authentication/authorization handlers so that I control who can store data in my storage (possibly using my existing auth system)

When integrating giftless into a project (probably for data storage e.g. from a client e.g. giftless-client-js) I want to understand the overall flow including how auth works and where data gets stored (and how i control that)

When considering using Giftless i want to understand what it does and why it is valuable (and why it is designed the way it is)

## Acceptance

* [x] Tutorial showing this running with local git and local giftless and cloud
  * [x] Deploy giftless locally (no auth) (with local storage)
  * [x] Use git with it e.g. Add lfsconfig manually ...
  * [x] Let's add proper cloud storage (google cloud) - not other providers are possible
  * [x] Let's add auth => Tutorial showing how use with jwt e.g. use giftless-client-js (even from node?) or giftless-client-py with this
    * [x] Generate jwt token on command line
    * [x] Use with code snippet which uses jwt and a client ...
    * [x] Shows direct uploading with git ...
* [x] Deployment e.g. docker
* [x] Docs deployed at giftless.datopian.com

## Tasks

**Comment by shevron** [comment]
Created two tutorials (currently available @ https://giftless.readthedocs.io/en/master/guides.html), more to come. Also created a ticket for Datopian DevOps to create a CNAME for giftless.datopian.com.

**Comment by shevron** [comment]
All done and should be available at giftless.datopian.com
